### PR TITLE
bootstrap in bytecode-only platform

### LINKED ISSUE #174: no support for bytecode-only platforms
I adapted ./bootstrap script https://github.com/ocaml-obuild/obuild/pull/173 to use no ocamlopt, but there’re other problems with it like

```
File "init.ml", line 98, characters 45-62:
Warning 3: deprecated: String.capitalize
Use String.capitalize_ascii instead.
COMPILING help
COMPILING install
COMPILING path_generated
COMPILING main
LINKING obuild.bootstrap
Configuring obuild-0.1.9...
uncaught exception
Fatal error: exception Obuild.Prog.ProgramNotFound("ocamlopt")
Called from unknown location
```

### PR DESCRIPTION
**Pull request by andyli**
Based on the work in #173. Fixes #174.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Hello, wouldn't it be possible to patch the existing bootstrap file instead of creating a new one?

**Comment by andyli** [comment]
On Mon, 21 May 2018, 08:02 UnixJunkie, <notifications@github.com> wrote:

> Hello, wouldn't it be possible to patch the existing bootstrap file
> instead of creating a new one?
>

Hi. Yes. But if your intention is to keep it simple, I would suggest
replacing the bootstrap script with bootstrap-bytecode, because the
bytecode bootstrap binary will also work in native platforms. I can add a
condition to create the final binary as native if possible.

>

**Comment by andyli** [comment]
It should be good to go now. I've tested installing it with opam `4.04.0+bytecode-only` and `4.06.0`.

**Comment by UnixJunkie** [comment]
if @jeromemaloberti integrates this and tags a new obuild version, then the opam CI tests will test this with many different versions of the compiler (though I'm not sure if any of them is a bytecode-only compiler).

**Comment by andyli** [comment]
BTW, before tagging a release, remember to update the version number in `obuild.obuild`, which is still at 0.1.9 right now.

**Comment by jeromemaloberti** [comment]
The script is fine, I didn't test it though, however the change in prog.ml means that obuild will not use ocamlopt when it is available. I would prefer that the configuration correctly uses the right compiler.
I will try to work on it.

**Comment by jeromemaloberti** [comment]
@andyli , actually, could you try to change getOcamlOpt () in prog.ml line 35 to add "ocamlc" in the list ?
It should fall back to ocamlc if ocamlopt is not found. It is a hack though.

**Comment by andyli** [comment]
I don't think my prog.ml change will affect using ocamlopt or not for actually building. That line is to call `-config`, which from my testing, all ocamlc, ocamlopt, ocamlc.opt, and ocamlopt.opt output the same result.

I do find an unrelated minor issue. Going to push one more commit now.

**Comment by jeromemaloberti** [comment]
Yes, you're right.
Another potential problem that worry me, is the default targets in gconf.ml, target_options_defaults. So, on platform with ocamlc only, the users will have to set explicitly executable-bytecode to true, and executable-native to false. Ideally, the configure command in the bootstrap should be the same on all platforms. I will think about it.

**Comment by andyli** [comment]
Yeah, I also considered making the default smart, but then I figured it could be done later. So, I kept this PR minimal.

**Comment by andyli** [comment]
Is there any problem with this PR? It is incremental that shouldn't break anything but enabled building obuild in bytecode-only platforms.

**Comment by jeromemaloberti** [comment]
Sorry, I was on holiday, and I missed the latest commit.

**Comment by UnixJunkie** [comment]
Hi Jerome, ping me if you create a new tag, I will update the opam package, as usual.

**Comment by UnixJunkie** [comment]
andyli reminded that we need a new tag to publish the fix

**Pull request merged**
